[package]
name = "gromit"
version = "0.1.0"
authors = ["Stephan Luther <kvsari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
num-traits = "0.2.8"
derive-getters = "0.0.8"
